# Site settings
title: Portfolio de Joel Mercier
email: hello@joelmercier.io
description: > # this means to ignore newlines until "baseurl:"
  Jeune développeur orienté front-end dynamique et soucieux de fournir un travail performant, je recherche actuellement un emploi à Strasbourg. Sur mon site vous pouvez découvrir mon profil ainsi que les réalisations que j'ai pu accomplir lors de mon apprentissage par exemple.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joelmercier.io" # the base hostname & protocol for your site
twitter_username: joelmrcr
github_username:  Joel-Mercier
linked_in_id: joel-mercier-a1450388

# Build settings
markdown: kramdown
highlighter: pygments
destination : _site/
exclude: ['node_modules', 'package.json', 'gulpfile.js', 'Gemfile', 'Gemfile.lock', 'sources', 'README.md', 'composer.json', 'composer.lock']
permalink: /:categories/:title/
paginate: 6
paginate_path: /blog/page:num
languages: ["fr", "en"]
excerpt_separator: "<!--split-->"
# exclude_from_localizations: ["img", "js", "css"]
collections:
  portfolio:
    permalink: /works/:title/
    output: true
  work_experiences:
    output: false
