# Site settings
title: Portfolio de Joel Mercier
email: jomercier@sfr.fr
description: > # this means to ignore newlines until "baseurl:"
  Joel Mercier - Développeur web
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jomercier.com" # the base hostname & protocol for your site
twitter_username: joelmrcr
github_username:  Joel-Mercier
linked_in_id: joel-mercier-a1450388

# Build settings
markdown: kramdown
highlighter: pygments
destination : _site/
exclude: ['node_modules', 'package.json', 'gulpfile.js', 'Gemfile', 'Gemfile.lock', 'sources', 'README.md', 'composer.json', 'composer.lock']
permalink: /:categories/:title/
paginate: 6
paginate_path: /blog/page:num
languages: ["fr", "en"]
excerpt_separator: "<!--split-->"
# exclude_from_localizations: ["img", "js", "css"]
collections:
  portfolio:
    permalink: /works/:title/
    output: true
  work_experiences:
    output: false
